# Generated by Django 4.2.29 on 2026-04-30 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_historicaldataset_systemsetting_historicalreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='alert',
            name='water_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='api.watersource'),
        ),
        migrations.AddField(
            model_name='watersource',
            name='battery',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watersource',
            name='installed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watersource',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watersource',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watersource',
            name='sensor_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
