# Generated by Django 4.2.29 on 2026-04-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alert_threshold_alert_title_alert_water_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorparameter',
            name='category',
            field=models.CharField(choices=[('micro', 'Microbiological'), ('physical', 'Physical / Aesthetic'), ('chemical', 'Chemical'), ('operational', 'Operational')], default='chemical', max_length=15),
        ),
        migrations.AddField(
            model_name='stationreading',
            name='free_chlorine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationreading',
            name='tds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watersource',
            name='measured_parameters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='sensorparameter',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sensorparameter',
            name='safe_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorparameter',
            name='safe_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorparameter',
            name='unit',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sensorparameter',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
