# Generated by Django 6.0.5 on 2026-06-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0003_alter_networkupload_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkupload',
            name='file_type',
            field=models.CharField(choices=[('shapefile', 'Shapefile'), ('epanet', 'EPANET .inp'), ('epanet_inp', 'EPANET .inp'), ('geojson', 'GeoJSON'), ('kml', 'KML/KMZ')], max_length=20),
        ),
    ]
