# Generated by Django 6.0.5 on 2026-06-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0004_alter_networkupload_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkupload',
            name='network_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
