# Generated by Django 6.0.5 on 2026-06-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0005_networkupload_network_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='waternetwork',
            name='is_schematic',
            field=models.BooleanField(default=False),
        ),
    ]
